import React, { useState, useMemo } from "react";
import { downloadICS } from './utils/icsExport';
import { Plus, Trash2, Calendar, FileText, Sparkles, BookOpen, Clock, Target, Upload, Download, X, ChevronRight, AlertCircle, Check } from "lucide-react";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { useLocalStorage } from './hooks/useLocalStorage';
import { buildGoogleCalendarUrl } from './utils/googleCalendar';

export default function App() {
  const [view, setView] = useLocalStorage("ssp-view", "today");
  const [subjects, setSubjects] = useLocalStorage("ssp-subjects", []);
  const [assignments, setAssignments] = useLocalStorage("ssp-assignments", []);
  const [materials, setMaterials] = useLocalStorage("ssp-materials", []);
  const [schedule, setSchedule] = useLocalStorage("ssp-schedule", null);
  const [generating, setGenerating] = useState(false);
  const [showAddSubject, setShowAddSubject] = useState(false);
  const [showAddAssignment, setShowAddAssignment] = useState(false);
  const [showUpload, setShowUpload] = useState(false);
  const [toast, setToast] = useState(null);
  const [gCalLinks, setGCalLinks] = useState([]);

  // Use local date (not UTC) so the day is correct for all time zones
  const todayStr = new Date().toLocaleDateString("en-CA"); // yields YYYY-MM-DD in local time

  const showToast = (msg) => {
    setToast(msg);
    setTimeout(() => setToast(null), 2500);
  };

  const generateSchedule = async () => {
    if (subjects.length === 0 || assignments.length === 0) {
      showToast("Add subjects and assignments first");
      return;
    }
    setGenerating(true);

    try {
      // ⚠️ SECURITY: VITE_ env vars are bundled into the client JS and visible to anyone
      // in DevTools or the built output. Before deploying publicly, move this call to
      // a backend endpoint (e.g. a Vercel/Netlify function) so the key stays server-side.
      const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
      if (!apiKey) {
        showToast("API key missing — check .env.local");
        setGenerating(false);
        return;
      }

      const genAI = new GoogleGenerativeAI(apiKey);
      const model = genAI.getGenerativeModel({
        model: "gemini-flash-latest",
        generationConfig: { responseMimeType: "application/json" },
      });

      const input = {
        today: todayStr,
        student: { available_hours_per_day: 3, preferred_study_time: "evening" },
        subjects: subjects.map((s) => ({ id: s.id, name: s.name, difficulty: s.difficulty })),
        assignments: assignments.map((a) => ({
          id: a.id, subject_id: a.subject_id, title: a.title,
          type: a.type, due_date: a.due_date, estimated_hours: a.estimated_hours,
        })),
        materials_available: materials.map((m) => m.subject_id),
      };

      const prompt = `You are an expert academic study planner helping a student build a realistic, personalized study schedule. Your goal is to reduce the student's stress by giving them clear, prioritized daily tasks they can actually complete.

You will receive a JSON object describing the student's subjects, assignments, available study time, and which subjects have uploaded study materials. You must respond with ONLY a valid JSON object matching the output schema below. No markdown. No code fences. No text before or after the JSON.

OUTPUT SCHEMA:
{
  "schedule": [
    {
      "date": "ISO date string",
      "sessions": [
        {
          "subject_id": string,
          "subject_name": string,
          "task": string (specific, actionable, max 80 chars),
          "duration_minutes": number (between 30 and 120, in 15-min increments),
          "priority": "high" | "medium" | "low",
          "reasoning": string (one sentence, max 100 chars, explains WHY this session today)
        }
      ]
    }
  ],
  "summary": string (2-3 sentences, friendly tone, explains the overall strategy)
}

PLANNING RULES:
1. Plan from "today" until the latest assignment due date, but no more than 14 days ahead.
2. Never schedule more total minutes per day than (available_hours_per_day * 60).
3. Prioritize by urgency, difficulty, and estimated_hours.
4. Spread practice across days. Use spaced repetition.
5. For exams, schedule lighter review in the final 1-2 days.
6. For essays/projects, schedule in phases (outline -> draft -> revise).
7. If a subject's id is in materials_available, occasionally suggest reviewing uploaded notes.
8. Include lighter days to avoid burnout.
9. Tasks must be specific and actionable.
10. Reasoning must be specific to that session.

INPUT:
${JSON.stringify(input, null, 2)}`;

      const result = await model.generateContent(prompt);
      const text = result.response.text();
      const parsed = JSON.parse(text);

      setSchedule(parsed);
      showToast("Plan generated by AI");
      setView("today");
    } catch (err) {
      console.error("Gemini error:", err);
      showToast("AI failed — check console (F12)");
    } finally {
      setGenerating(false);
    }
  };

  const todaySessions = useMemo(() => {
    if (!schedule) return [];
    const today = schedule.schedule.find((d) => d.date === todayStr);
    return today ? today.sessions : (schedule.schedule[0]?.sessions || []);
  }, [schedule, todayStr]);

  const upcomingDeadlines = useMemo(() => {
    return [...assignments]
      .filter((a) => new Date(a.due_date) >= new Date(todayStr))
      .sort((a, b) => new Date(a.due_date) - new Date(b.due_date))
      .slice(0, 3);
  }, [assignments, todayStr]);

  const daysUntil = (dateStr) => {
    const diff = Math.ceil((new Date(dateStr) - new Date(todayStr)) / (1000 * 60 * 60 * 24));
    if (diff === 0) return "today";
    if (diff === 1) return "tomorrow";
    if (diff < 0) return "overdue";
    return `in ${diff} days`;
  };

  const subjectName = (id) => subjects.find((s) => s.id === id)?.name || "Unknown";

  const exportICS = () => {
    if (!schedule || Object.keys(schedule).length === 0) {
      showToast('No schedule to export yet. Generate one first!');
      return;
    }
    try {
      const count = downloadICS(schedule, 'study-schedule.ics');
      showToast(`Exported ${count} sessions to calendar file`);
    } catch (err) {
      console.error(err);
      showToast('Failed to export calendar file');
    }
  };

  const syncGoogle = () => {
    if (!schedule || todaySessions.length === 0) {
      showToast("No sessions today to sync");
      return;
    }
    const today = schedule.schedule.find((d) => d.date.startsWith(todayStr))
      || schedule.schedule[0];

    // Open only the first URL directly (browsers block multiple popups triggered at once).
    // For the remaining sessions, build links and let the user click them.
    const urls = todaySessions.map((s) => buildGoogleCalendarUrl(s, today.date));
    window.open(urls[0], '_blank');

    if (urls.length > 1) {
      // Store remaining URLs so the UI can render them as clickable links
      setGCalLinks(urls.slice(1));
      showToast(`Opened session 1 — click the links below for the rest`);
    } else {
      showToast("Opened in Google Calendar");
    }
  };

  const todayDisplay = new Date(todayStr).toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" });

  return (
    <div className="min-h-screen bg-stone-50 text-stone-900" style={{ fontFamily: "'Fraunces', Georgia, serif" }}>

      {toast && (
        <div className="fixed top-6 left-1/2 -translate-x-1/2 z-50 bg-stone-900 text-stone-50 px-5 py-3 rounded-full text-sm flex items-center gap-2 shadow-2xl" style={{ fontFamily: "'JetBrains Mono', monospace" }}>
          <Check className="w-4 h-4" />
          {toast}
        </div>
      )}

      <header className="border-b border-stone-200 bg-stone-50/80 backdrop-blur sticky top-0 z-40">
        <div className="max-w-6xl mx-auto px-6 py-5 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-stone-900 text-amber-300 flex items-center justify-center rounded-lg">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <div className="text-2xl font-bold leading-none tracking-tight">Smart Study Planner</div>
              <div className="text-xs text-stone-500 mt-1" style={{ fontFamily: "'JetBrains Mono', monospace" }}>AI-POWERED</div>
            </div>
          </div>
          <nav className="flex items-center gap-1">
            {[
              { id: "today", label: "Today" },
              { id: "schedule", label: "Schedule" },
              { id: "subjects", label: "Subjects" },
              { id: "materials", label: "Materials" },
            ].map((tab) => (
              <button
                key={tab.id}
                onClick={() => setView(tab.id)}
                className={`px-4 py-2 rounded-full text-sm transition-all ${view === tab.id ? "bg-stone-900 text-stone-50" : "text-stone-600 hover:bg-stone-200"}`}
              >
                {tab.label}
              </button>
            ))}
          </nav>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-6 py-10">

        {view === "today" && (
          <div className="space-y-8">
            <div className="flex items-end justify-between">
              <div>
                <div className="text-xs text-stone-500 uppercase tracking-wider mb-2" style={{ fontFamily: "'JetBrains Mono', monospace" }}>{todayDisplay}</div>
                <h1 className="text-6xl font-bold tracking-tight leading-none">Today<span className="text-amber-500">.</span></h1>
              </div>
              <button onClick={generateSchedule} disabled={generating} className="bg-stone-900 text-stone-50 px-6 py-3 rounded-full text-sm font-medium hover:bg-stone-700 transition flex items-center gap-2 disabled:opacity-50">
                {generating ? (<><div className="w-4 h-4 border-2 border-stone-50 border-t-transparent rounded-full animate-spin" /> Generating...</>) : (<><Sparkles className="w-4 h-4" /> {schedule ? "Regenerate plan" : "Generate plan"}</>)}
              </button>
            </div>

            {!schedule && (
              <div className="border-2 border-dashed border-stone-300 rounded-3xl p-16 text-center">
                <Sparkles className="w-12 h-12 mx-auto text-stone-400 mb-4" />
                <div className="text-2xl font-semibold mb-2">No plan yet</div>
                <div className="text-stone-600 mb-6">Click "Generate plan" to let the AI build your study schedule.</div>
              </div>
            )}

            {schedule && (
              <>
                <div className="bg-amber-100 border border-amber-200 rounded-3xl p-6 flex gap-4">
                  <div className="w-10 h-10 bg-amber-500 text-white rounded-full flex items-center justify-center flex-shrink-0">
                    <Sparkles className="w-5 h-5" />
                  </div>
                  <div>
                    <div className="text-xs uppercase tracking-wider text-amber-800 mb-1" style={{ fontFamily: "'JetBrains Mono', monospace" }}>AI Strategy</div>
                    <div className="text-stone-800 leading-relaxed">{schedule.summary}</div>
                  </div>
                </div>

                <div className="space-y-4">
                  <div className="text-sm uppercase tracking-wider text-stone-500" style={{ fontFamily: "'JetBrains Mono', monospace" }}>
                    {todaySessions.length} sessions · {todaySessions.reduce((s, x) => s + x.duration_minutes, 0)} min total
                  </div>

                  {todaySessions.map((s, i) => (
                    <div key={i} className="group bg-white border border-stone-200 rounded-3xl p-6 hover:border-stone-400 transition">
                      <div className="flex items-start gap-5">
                        <div className={`w-1 self-stretch rounded-full ${s.priority === "high" ? "bg-red-500" : s.priority === "medium" ? "bg-amber-500" : "bg-stone-300"}`} />
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-2">
                            <div className="text-xs uppercase tracking-wider text-stone-500" style={{ fontFamily: "'JetBrains Mono', monospace" }}>{s.subject_name}</div>
                            <div className="text-stone-300">·</div>
                            <div className="text-xs text-stone-500 flex items-center gap-1" style={{ fontFamily: "'JetBrains Mono', monospace" }}>
                              <Clock className="w-3 h-3" /> {s.duration_minutes} min
                            </div>
                          </div>
                          <div className="text-2xl font-semibold leading-snug mb-3">{s.task}</div>
                          <div className="text-sm text-stone-500 italic">{s.reasoning}</div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>

                <div className="flex gap-3 pt-4">
                  <button onClick={syncGoogle} className="flex-1 bg-white border border-stone-300 hover:border-stone-500 rounded-full px-5 py-3 text-sm font-medium transition flex items-center justify-center gap-2">
                    <Calendar className="w-4 h-4" /> Sync to Google Calendar
                  </button>
                  <button onClick={exportICS} className="flex-1 bg-white border border-stone-300 hover:border-stone-500 rounded-full px-5 py-3 text-sm font-medium transition flex items-center justify-center gap-2">
                    <Download className="w-4 h-4" /> Download .ics
                  </button>
                </div>

                {gCalLinks.length > 0 && (
                  <div className="bg-stone-100 border border-stone-200 rounded-2xl p-4 space-y-2">
                    <div className="text-xs uppercase tracking-wider text-stone-500 mb-2" style={{ fontFamily: "'JetBrains Mono', monospace" }}>
                      Click to add remaining sessions to Google Calendar
                    </div>
                    {gCalLinks.map((url, i) => (
                      <a key={i} href={url} target="_blank" rel="noopener noreferrer"
                        className="flex items-center gap-2 text-sm text-stone-700 hover:text-stone-900 hover:underline">
                        <Calendar className="w-3 h-3 flex-shrink-0" />
                        {todaySessions[i + 1]?.subject_name}: {todaySessions[i + 1]?.task}
                      </a>
                    ))}
                    <button onClick={() => setGCalLinks([])} className="text-xs text-stone-400 hover:text-stone-600 mt-1">Dismiss</button>
                  </div>
                )}
              </>
            )}

            <div className="grid grid-cols-3 gap-4 pt-4">
              <div className="bg-white border border-stone-200 rounded-2xl p-5">
                <div className="text-xs uppercase tracking-wider text-stone-500 mb-3" style={{ fontFamily: "'JetBrains Mono', monospace" }}>Upcoming</div>
                <div className="space-y-3">
                  {upcomingDeadlines.map((a) => (
                    <div key={a.id} className="flex items-center justify-between">
                      <div>
                        <div className="font-medium text-sm">{a.title}</div>
                        <div className="text-xs text-stone-500">{subjectName(a.subject_id)}</div>
                      </div>
                      <div className="text-xs text-stone-600" style={{ fontFamily: "'JetBrains Mono', monospace" }}>{daysUntil(a.due_date)}</div>
                    </div>
                  ))}
                </div>
              </div>
              <div className="bg-white border border-stone-200 rounded-2xl p-5">
                <div className="text-xs uppercase tracking-wider text-stone-500 mb-3" style={{ fontFamily: "'JetBrains Mono', monospace" }}>Subjects</div>
                <div className="text-4xl font-bold">{subjects.length}</div>
                <div className="text-xs text-stone-500 mt-1">active courses</div>
              </div>
              <div className="bg-white border border-stone-200 rounded-2xl p-5">
                <div className="text-xs uppercase tracking-wider text-stone-500 mb-3" style={{ fontFamily: "'JetBrains Mono', monospace" }}>Materials</div>
                <div className="text-4xl font-bold">{materials.length}</div>
                <div className="text-xs text-stone-500 mt-1">PDF{materials.length !== 1 ? "s" : ""} uploaded</div>
              </div>
            </div>
          </div>
        )}

        {view === "schedule" && (
          <div className="space-y-6">
            <div>
              <div className="text-xs text-stone-500 uppercase tracking-wider mb-2" style={{ fontFamily: "'JetBrains Mono', monospace" }}>Your full plan</div>
              <h1 className="text-6xl font-bold tracking-tight leading-none">Schedule<span className="text-amber-500">.</span></h1>
            </div>

            {!schedule ? (
              <div className="border-2 border-dashed border-stone-300 rounded-3xl p-16 text-center">
                <Calendar className="w-12 h-12 mx-auto text-stone-400 mb-4" />
                <div className="text-xl font-semibold mb-4">No schedule yet</div>
                <button onClick={generateSchedule} className="bg-stone-900 text-stone-50 px-6 py-3 rounded-full text-sm">Generate plan</button>
              </div>
            ) : (
              <div className="space-y-6">
                {schedule.schedule.map((day) => {
                  const date = new Date(day.date);
                  const dayName = date.toLocaleDateString("en-US", { weekday: "long" });
                  const dayNum = date.getDate();
                  const monthName = date.toLocaleDateString("en-US", { month: "short" });
                  return (
                    <div key={day.date} className="flex gap-6">
                      <div className="w-20 flex-shrink-0 text-right">
                        <div className="text-4xl font-bold leading-none">{dayNum}</div>
                        <div className="text-xs uppercase tracking-wider text-stone-500 mt-1" style={{ fontFamily: "'JetBrains Mono', monospace" }}>{monthName}</div>
                        <div className="text-xs text-stone-500 mt-1">{dayName}</div>
                      </div>
                      <div className="flex-1 space-y-2 border-l border-stone-200 pl-6">
                        {day.sessions.length === 0 ? (
                          <div className="text-sm text-stone-400 italic py-2">Rest day</div>
                        ) : (
                          day.sessions.map((s, i) => (
                            <div key={i} className="bg-white border border-stone-200 rounded-2xl p-4 flex items-center gap-4">
                              <div className={`w-1 self-stretch rounded-full ${s.priority === "high" ? "bg-red-500" : s.priority === "medium" ? "bg-amber-500" : "bg-stone-300"}`} />
                              <div className="flex-1">
                                <div className="text-xs text-stone-500 mb-1" style={{ fontFamily: "'JetBrains Mono', monospace" }}>{s.subject_name} · {s.duration_minutes}min</div>
                                <div className="font-medium">{s.task}</div>
                                <div className="text-xs text-stone-500 italic mt-1">{s.reasoning}</div>
                              </div>
                            </div>
                          ))
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        )}

        {view === "subjects" && (
          <div className="space-y-8">
            <div className="flex items-end justify-between">
              <div>
                <div className="text-xs text-stone-500 uppercase tracking-wider mb-2" style={{ fontFamily: "'JetBrains Mono', monospace" }}>Manage your courses</div>
                <h1 className="text-6xl font-bold tracking-tight leading-none">Subjects<span className="text-amber-500">.</span></h1>
              </div>
              <button onClick={() => setShowAddSubject(true)} className="bg-stone-900 text-stone-50 px-5 py-3 rounded-full text-sm flex items-center gap-2">
                <Plus className="w-4 h-4" /> Add subject
              </button>
            </div>

            <div className="grid grid-cols-2 gap-4">
              {subjects.map((s) => (
                <div key={s.id} className="bg-white border border-stone-200 rounded-3xl p-6 group">
                  <div className="flex items-start justify-between mb-4">
                    <BookOpen className="w-6 h-6 text-stone-400" />
                    <button onClick={() => { setSubjects(subjects.filter((x) => x.id !== s.id)); setAssignments(assignments.filter((a) => a.subject_id !== s.id)); }} className="opacity-0 group-hover:opacity-100 transition text-stone-400 hover:text-red-500">
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                  <div className="text-2xl font-semibold mb-2">{s.name}</div>
                  <div className="flex items-center gap-2 mb-4">
                    <div className="text-xs uppercase tracking-wider text-stone-500" style={{ fontFamily: "'JetBrains Mono', monospace" }}>Difficulty</div>
                    <div className="flex gap-1">
                      {[1, 2, 3, 4, 5].map((n) => (
                        <div key={n} className={`w-2 h-2 rounded-full ${n <= s.difficulty ? "bg-stone-900" : "bg-stone-200"}`} />
                      ))}
                    </div>
                  </div>
                </div>
              ))}
            </div>

            <div className="pt-8 border-t border-stone-200">
              <div className="flex items-end justify-between mb-6">
                <h2 className="text-3xl font-bold tracking-tight">Assignments & Exams</h2>
                <button onClick={() => setShowAddAssignment(true)} className="bg-stone-900 text-stone-50 px-5 py-3 rounded-full text-sm flex items-center gap-2">
                  <Plus className="w-4 h-4" /> Add
                </button>
              </div>
              <div className="space-y-2">
                {assignments.map((a) => (
                  <div key={a.id} className="bg-white border border-stone-200 rounded-2xl p-4 flex items-center gap-4 group">
                    <div className={`w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0 ${a.type === "exam" ? "bg-red-100 text-red-600" : a.type === "essay" ? "bg-amber-100 text-amber-700" : "bg-stone-100 text-stone-600"}`}>
                      {a.type === "exam" ? <Target className="w-5 h-5" /> : <FileText className="w-5 h-5" />}
                    </div>
                    <div className="flex-1">
                      <div className="font-medium">{a.title}</div>
                      <div className="text-xs text-stone-500" style={{ fontFamily: "'JetBrains Mono', monospace" }}>
                        {subjectName(a.subject_id)} · {a.estimated_hours}h · due {daysUntil(a.due_date)}
                      </div>
                    </div>
                    <button onClick={() => setAssignments(assignments.filter((x) => x.id !== a.id))} className="opacity-0 group-hover:opacity-100 transition text-stone-400 hover:text-red-500">
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {view === "materials" && (
          <div className="space-y-8">
            <div className="flex items-end justify-between">
              <div>
                <div className="text-xs text-stone-500 uppercase tracking-wider mb-2" style={{ fontFamily: "'JetBrains Mono', monospace" }}>AI-generated study notes</div>
                <h1 className="text-6xl font-bold tracking-tight leading-none">Materials<span className="text-amber-500">.</span></h1>
              </div>
              <button onClick={() => setShowUpload(true)} className="bg-stone-900 text-stone-50 px-5 py-3 rounded-full text-sm flex items-center gap-2">
                <Upload className="w-4 h-4" /> Upload PDF
              </button>
            </div>

            {materials.length === 0 ? (
              <div className="border-2 border-dashed border-stone-300 rounded-3xl p-16 text-center">
                <FileText className="w-12 h-12 mx-auto text-stone-400 mb-4" />
                <div className="text-xl font-semibold mb-2">No materials yet</div>
                <div className="text-stone-600">Upload a PDF and the AI will generate study notes from it.</div>
              </div>
            ) : (
              <div className="space-y-4">
                {materials.map((m) => (
                  <div key={m.id} className="bg-white border border-stone-200 rounded-3xl p-6 group">
                    <div className="flex items-start gap-4">
                      <div className="w-12 h-12 bg-stone-900 text-amber-300 rounded-xl flex items-center justify-center flex-shrink-0">
                        <FileText className="w-6 h-6" />
                      </div>
                      <div className="flex-1">
                        <div className="text-xs uppercase tracking-wider text-stone-500 mb-1" style={{ fontFamily: "'JetBrains Mono', monospace" }}>{subjectName(m.subject_id)}</div>
                        <div className="text-xl font-semibold mb-3">{m.filename}</div>
                        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4">
                          <div className="text-xs uppercase tracking-wider text-amber-800 mb-2 flex items-center gap-1" style={{ fontFamily: "'JetBrains Mono', monospace" }}>
                            <Sparkles className="w-3 h-3" /> AI-generated notes
                          </div>
                          <div className="text-sm text-stone-700 leading-relaxed">{m.notes}</div>
                        </div>
                      </div>
                      <button onClick={() => setMaterials(materials.filter((x) => x.id !== m.id))} className="opacity-0 group-hover:opacity-100 transition text-stone-400 hover:text-red-500">
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

      </main>

      {showAddSubject && (
        <Modal onClose={() => setShowAddSubject(false)} title="Add subject">
          <SubjectForm onSubmit={(s) => { setSubjects([...subjects, { ...s, id: `s${Date.now()}` }]); setShowAddSubject(false); showToast("Subject added"); }} />
        </Modal>
      )}

      {showAddAssignment && (
        <Modal onClose={() => setShowAddAssignment(false)} title="Add assignment">
          <AssignmentForm subjects={subjects} onSubmit={(a) => { setAssignments([...assignments, { ...a, id: `a${Date.now()}` }]); setShowAddAssignment(false); showToast("Assignment added"); }} />
        </Modal>
      )}

      {showUpload && (
        <Modal onClose={() => setShowUpload(false)} title="Upload PDF material">
          <UploadForm subjects={subjects} onSubmit={(m) => { setMaterials([...materials, { ...m, id: `m${Date.now()}` }]); setShowUpload(false); showToast("Notes generated by AI"); }} />
        </Modal>
      )}
    </div>
  );
}

function Modal({ children, onClose, title }) {
  return (
    <div className="fixed inset-0 bg-stone-900/50 backdrop-blur-sm z-50 flex items-center justify-center p-6" onClick={onClose}>
      <div className="bg-stone-50 rounded-3xl max-w-md w-full p-8" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between mb-6">
          <h2 className="text-2xl font-bold tracking-tight">{title}</h2>
          <button onClick={onClose} className="text-stone-400 hover:text-stone-900">
            <X className="w-5 h-5" />
          </button>
        </div>
        {children}
      </div>
    </div>
  );
}

function SubjectForm({ onSubmit }) {
  const [name, setName] = useState("");
  const [difficulty, setDifficulty] = useState(3);
  return (
    <div className="space-y-5">
      <div>
        <label className="text-xs uppercase tracking-wider text-stone-500 block mb-2" style={{ fontFamily: "'JetBrains Mono', monospace" }}>Name</label>
        <input value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Organic Chemistry" className="w-full bg-white border border-stone-300 rounded-xl px-4 py-3 focus:outline-none focus:border-stone-900" />
      </div>
      <div>
        <label className="text-xs uppercase tracking-wider text-stone-500 block mb-3" style={{ fontFamily: "'JetBrains Mono', monospace" }}>Difficulty</label>
        <div className="flex gap-2">
          {[1, 2, 3, 4, 5].map((n) => (
            <button key={n} onClick={() => setDifficulty(n)} className={`flex-1 py-3 rounded-xl border transition ${difficulty >= n ? "bg-stone-900 border-stone-900 text-stone-50" : "bg-white border-stone-300 text-stone-400"}`}>{n}</button>
          ))}
        </div>
      </div>
      <button onClick={() => name.trim() && onSubmit({ name: name.trim(), difficulty })} disabled={!name.trim()} className="w-full bg-stone-900 text-stone-50 py-3 rounded-full font-medium disabled:opacity-30">
        Add subject
      </button>
    </div>
  );
}

function AssignmentForm({ subjects, onSubmit }) {
  const [title, setTitle] = useState("");
  const [subject_id, setSubjectId] = useState(subjects[0]?.id || "");
  const [type, setType] = useState("homework");
  const [due_date, setDueDate] = useState("");
  const [estimated_hours, setHours] = useState(2);

  if (subjects.length === 0) {
    return <div className="text-center py-8 text-stone-500">Add a subject first.</div>;
  }

  return (
    <div className="space-y-4">
      <div>
        <label className="text-xs uppercase tracking-wider text-stone-500 block mb-2" style={{ fontFamily: "'JetBrains Mono', monospace" }}>Title</label>
        <input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g. Final project" className="w-full bg-white border border-stone-300 rounded-xl px-4 py-3 focus:outline-none focus:border-stone-900" />
      </div>
      <div>
        <label className="text-xs uppercase tracking-wider text-stone-500 block mb-2" style={{ fontFamily: "'JetBrains Mono', monospace" }}>Subject</label>
        <select value={subject_id} onChange={(e) => setSubjectId(e.target.value)} className="w-full bg-white border border-stone-300 rounded-xl px-4 py-3 focus:outline-none focus:border-stone-900">
          {subjects.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}
        </select>
      </div>
      <div className="grid grid-cols-2 gap-3">
        <div>
          <label className="text-xs uppercase tracking-wider text-stone-500 block mb-2" style={{ fontFamily: "'JetBrains Mono', monospace" }}>Type</label>
          <select value={type} onChange={(e) => setType(e.target.value)} className="w-full bg-white border border-stone-300 rounded-xl px-4 py-3 focus:outline-none focus:border-stone-900">
            <option value="homework">Homework</option>
            <option value="essay">Essay</option>
            <option value="exam">Exam</option>
            <option value="project">Project</option>
          </select>
        </div>
        <div>
          <label className="text-xs uppercase tracking-wider text-stone-500 block mb-2" style={{ fontFamily: "'JetBrains Mono', monospace" }}>Hours</label>
          <input type="number" value={estimated_hours} onChange={(e) => setHours(Number(e.target.value))} min="1" max="40" className="w-full bg-white border border-stone-300 rounded-xl px-4 py-3 focus:outline-none focus:border-stone-900" />
        </div>
      </div>
      <div>
        <label className="text-xs uppercase tracking-wider text-stone-500 block mb-2" style={{ fontFamily: "'JetBrains Mono', monospace" }}>Due date</label>
        <input type="date" value={due_date} onChange={(e) => setDueDate(e.target.value)} className="w-full bg-white border border-stone-300 rounded-xl px-4 py-3 focus:outline-none focus:border-stone-900" />
      </div>
      <button onClick={() => title.trim() && due_date && onSubmit({ title: title.trim(), subject_id, type, due_date, estimated_hours })} disabled={!title.trim() || !due_date} className="w-full bg-stone-900 text-stone-50 py-3 rounded-full font-medium disabled:opacity-30">
        Add assignment
      </button>
    </div>
  );
}

function UploadForm({ subjects, onSubmit }) {
  const [subject_id, setSubjectId] = useState(subjects[0]?.id || "");
  const [file, setFile] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState("");

  if (subjects.length === 0) {
    return <div className="text-center py-8 text-stone-500">Add a subject first.</div>;
  }

  const MAX_BYTES = 5 * 1024 * 1024;

  const handleFileChange = (e) => {
    setError("");
    const f = e.target.files?.[0];
    if (!f) return;
    if (f.type !== "application/pdf") {
      setError("Please select a PDF file.");
      return;
    }
    if (f.size > MAX_BYTES) {
      setError("File too large. Max 5MB.");
      return;
    }
    setFile(f);
  };

  const fileToBase64 = (f) =>
    new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result.split(",")[1]);
      reader.onerror = () => reject(new Error("Failed to read file"));
      reader.readAsDataURL(f);
    });

  const handleSubmit = async () => {
    if (!file) return;
    setGenerating(true);
    setError("");

    try {
      const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
      if (!apiKey) {
        setError("API key missing — check .env.local");
        setGenerating(false);
        return;
      }

      const base64Data = await fileToBase64(file);
      const genAI = new GoogleGenerativeAI(apiKey);
      const model = genAI.getGenerativeModel({ model: "gemini-flash-latest" });

      const prompt = `You are a study assistant. Read the attached PDF and produce BRIEF study notes for a student.

Your response should be a single paragraph (4-6 sentences, max 600 characters) covering:
- The 2-3 most important key concepts
- What the student should focus on most
- Any common mistakes to avoid
- One quick study tip

Write in a friendly, direct tone. Do NOT use bullet points, headings, or markdown. Plain prose only. Do NOT include any preamble like "Here are the notes:" — just the notes themselves.`;

      const result = await model.generateContent([
        { inlineData: { mimeType: "application/pdf", data: base64Data } },
        { text: prompt },
      ]);

      const notes = result.response.text().trim();

      if (!notes) {
        setError("AI returned empty notes. Try again.");
        setGenerating(false);
        return;
      }

      onSubmit({ subject_id, filename: file.name, notes });
    } catch (err) {
      console.error("PDF upload error:", err);
      setError("Failed to generate notes. Check console (F12).");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-4">
      <div>
        <label className="text-xs uppercase tracking-wider text-stone-500 block mb-2" style={{ fontFamily: "'JetBrains Mono', monospace" }}>Subject</label>
        <select value={subject_id} onChange={(e) => setSubjectId(e.target.value)} className="w-full bg-white border border-stone-300 rounded-xl px-4 py-3 focus:outline-none focus:border-stone-900">
          {subjects.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}
        </select>
      </div>

      <label className="w-full border-2 border-dashed border-stone-300 hover:border-stone-500 rounded-2xl py-10 transition flex flex-col items-center gap-2 cursor-pointer">
        <Upload className="w-8 h-8 text-stone-400" />
        <div className="text-sm text-stone-600">{file ? file.name : "Click to select PDF"}</div>
        <div className="text-xs text-stone-400">Max 5MB · text-based PDFs only</div>
        <input type="file" accept="application/pdf" onChange={handleFileChange} className="hidden" />
      </label>

      {error && (
        <div className="bg-red-50 border border-red-200 rounded-xl p-3 flex gap-2 text-xs text-red-800">
          <AlertCircle className="w-4 h-4 flex-shrink-0 mt-0.5" />
          <div>{error}</div>
        </div>
      )}

      <div className="bg-amber-50 border border-amber-200 rounded-xl p-3 flex gap-2 text-xs text-amber-800">
        <AlertCircle className="w-4 h-4 flex-shrink-0 mt-0.5" />
        <div>The AI will read your PDF and generate study notes automatically.</div>
      </div>

      <button onClick={handleSubmit} disabled={!file || generating} className="w-full bg-stone-900 text-stone-50 py-3 rounded-full font-medium disabled:opacity-30 flex items-center justify-center gap-2">
        {generating ? (<><div className="w-4 h-4 border-2 border-stone-50 border-t-transparent rounded-full animate-spin" /> AI is reading...</>) : (<><Sparkles className="w-4 h-4" /> Generate notes</>)}
      </button>
    </div>
  );
}
